name: code assurance

on:
  workflow_call:
    inputs:
      php:
        default: "8.3"
        type: string
      config_file:
        required: true
        type: string

jobs:
  rector:
    if: github.actor != 'dependabot[bot]'
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none
      
      - name: Composer Cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Rector Cache
        uses: actions/cache@v4
        with:
          path: /tmp/rector
          key: rector-${{ github.run_id }}
          restore-keys: rector-

      - run: mkdir -p /tmp/rector

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-progress --prefer-dist --optimize-autoloader

      - name: Prepare Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Rector
        run: php vendor/bin/rector process --config=${{ inputs.config_file }} --dry-run --output-format=OUTPUT-FORMAT
